### ISSUE TITLE
Homework Moodle upload

### ISSUE THREAD

**Issue by szabolcs-kerekes** [daroczig/CEU-R-skills#1]
Hi,

Would it be possible to upload pdfs (e.g. markdown file in pdf) to Moodle, or is it set to "online text" format for submission on purpose? I could not find a way to upload any documents, currently it seems to only allow text entered into a box. 

Thanks,
Szabolcs

**Comment by daroczig** [comment]
Sorry, @szabolcs-kerekes, this was set to "online text" on purpose so that we can provide comments directly on your submission instead of doing that in PDF/Word/other random formats that can be uploaded to Moodle. We might change this from next week.
