### ISSUE TITLE
Shiny publish error

### ISSUE THREAD

**Issue by BenceToth** [daroczig/CEU-R-skills#3]
Dear Gergely,

I spent whole days trying to figure out this problem without any luck.
I finished the final assignment, Shiny runs without a problem in the R console.
However, when I try to publish it to ShinyApps, I get the following:
"An error has occurred. Check your logs or contact the app author for clarification." in the browser.
I used to have an additional message in the console: 
"incomplete final line found by readTableHeader on 'raw' (Using default: en_US)". 
I changed the region settings to US English on my computer, and I don't have this error anymore.
Everythings seems to run smoothly, ending in "Deployment completed: https://bence-l-toth.shinyapps.io/finalassignment/". However, checking the url in the browser, I still get that "very informative" error message.

What could be the issue behind?

**Comment by daroczig** [comment]
Can you please check your app logs after logging into shinyapps.io? The error messages in the ap log should help you find out what's the problem. Feel free to paste the actual errors messages from there in this thread. You can find more hints at https://support.rstudio.com/hc/en-us/articles/229848967-Why-does-my-app-work-locally-but-not-on-shinyapps-io-

**Comment by BenceToth** [comment]
Thank you!
It was an issue of using an absolute file path.
